### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by lufzle** [angulartics/angulartics-localytics#1]
@joehalliwell, given that this was your contribution, do you think maybe you could find some time taking a role here?

**Comment by joehalliwell** [comment]
Sure! I'm not using the plugin on any current projects which isn't ideal -- but I'd be very happy to help out!

**Comment by lufzle** [comment]
Thanks! Having someone familiar with Localytics (at least more familiar than me, for sure) would be helpful. Making you a project collaborator then. Thanks again!

**Comment by joehalliwell** [comment]
:+1:
